### PR TITLE
ESLint 4

### PR DESCRIPTION
**Pull request by keeganstreet**

### CODE REVIEW

**Comment by jennasalau** [comment]
Looks good Keegan! 👍 

Just need to add some notes to `CHANGELOG.md`

If you're planning a release I might quickly sneak in a PR too.. I just realised I accidentally implemented a deprecated rule in our React rules. oops.

**Comment by keeganstreet** [comment]
Thanks Jenna, I think we should merge your PR first and make a patch release, then merge this one and make a major release, since its a new major release of ESLint. I'll update the changelog in this PR.

**Comment by keeganstreet** [comment]
I have now updated the changelog

**Comment by keeganstreet** [comment]
Note: this only failed CI because we haven't yet published version 3.0.0

**Pull request merged**
