### PR TITLE
Incorporating a new react config package

### PR DESCRIPTION
**Pull request by jennasalau**
Hey guys,

I've made some "sizable" changes to this repo to bring in React linting support. We should perhaps look at adding an Angular package soon too.

Main changes:

1) Moved the root package into `/packages/eslint-config-deloitte`
2) Added new react package into `/packages/eslint-config-deloitte-react`

For context, this one repo will now publish two NPM packages.

I've also bumped the major version number, pending a PR success I would like to publish these two packages as version 2 to ensure existing projects don't get these changes automatically.

### CODE REVIEW

**Comment by keeganstreet** [comment]
Why do we need to publish two packages to npm rather than using an eslintrc.js config like this in React projects?

```
module.exports = {
	extends: [
		'eslint-config-deloitte/react'
	]
};
```

**Comment by jennasalau** [comment]
Hey Keegan,

I originally went that route but decided against it in the end due to the following justification.

We will need to list `eslint-plugin-react` and `eslint-plugin-jsx-a11y` as two more peer dependencies. Unfortunately regardless if you choose to use the `eslint-config-deloitte/react` or not, you will still need to install them.

I was conscious that not all our projects use React so thought it would be unfair to enforce these packages onto them.

I'm more than happy to go back to the one package if this is not an issue? I also agree multiple readme's is not ideal.

**Comment by keeganstreet** [comment]
Hi Jenna,

Good points. I agree we should minimise dependencies where possible. `eslint-plugin-react` and `eslint-plugin-jsx-a11y` are required for linting React code bases but they would add unnecessary bloat in other projects. This is a strong argument for publishing two separate packages to npm.

Maybe we could make the two package readmes really light weight, basically just with a link to the root level readme. Otherwise if we have three full readmes in this repo it will be a nightmare to maintain documentation.

**Comment by jennasalau** [comment]
Okay I've update the root readme to this https://github.com/jennasalau/eslint-config-deloitte (obviously the links wont work until merged).

Then I just realised Keegan suggested the opposite to hold all the docs on the root one instead doh.. I can update, if we do it that way though, when we publish the packages to NPM.. the docs on the NPM site will just be a link to Github is that okay?

**Comment by keeganstreet** [comment]
> Then I just realised Keegan suggested the opposite to hold all the docs on the root one instead doh.. I can update, if we do it that way though, when we publish the packages to NPM.. the docs on the NPM site will just be a link to Github is that okay?
I think this is OK, otherwise we have to maintain one readme per package even though they are 90% the same.

**Comment by jennasalau** [comment]
Okay, I've updated the docs. Let me know if any of you have any more feedback :)

**Pull request merged**
